/* Pure operations for optional, snapshot-based practice. */
(function(root){'use strict';const node=typeof module!=='undefined'&&module.exports,L=node?require('./learning-core.js'):root.StudyLearningCore;
const clone=x=>JSON.parse(JSON.stringify(x)),text=(v,n=20000)=>typeof v==='string'&&v.length<=n;
const validSentence=s=>!!s&&text(s.id,50000)&&text(s.articleKey,200)&&Number.isInteger(s.paragraph)&&s.paragraph>=0&&text(s.en)&&!!s.en.trim()&&text(s.reference)&&['sentence','paragraph'].includes(s.referenceKind);
function capture(x,s){if(!validSentence(s))throw Error('没有可暂存的完整句子。');if(x.pendingSentences.some(r=>r.id===s.id&&r.status==='pending'))return false;const old=x.pendingSentences.find(r=>r.id===s.id);if(old)old.status='pending';else x.pendingSentences.push({...clone(s),capturedAt:new Date().toISOString(),status:'pending'});return true;}
function transfer(data,card){for(const[k,w]of Object.entries(data.words)){if(w.word.toLowerCase()!==card.word.toLowerCase())continue;for(const u of w.uses){if(u.sense.trim()!==card.sense.trim())continue;const s=L.usage(data,k,u);if(s&&s.context!==card.context)return s;}}return null;}
function buildRound(data,learning,x,{limit=5,mode='mixed',transferMode=false}={}){const items=[];if(['mixed','words'].includes(mode))for(const c of learning.cards){const t=transferMode?transfer(data,c):null;items.push({id:c.id,sourceRecordId:c.id,kind:'word',snapshot:clone(t||c),mode:t?'transfer':'saved',order:learning.attempts[c.id]?.rating==='wrong-sense'?0:learning.attempts[c.id]?.rating==='known'?3:1,at:0});}if(['mixed','sentences'].includes(mode))for(const c of learning.notes.filter(c=>!c.resolved))items.push({id:c.id,sourceRecordId:c.id,kind:'sentence',snapshot:clone(c),mode:'saved',order:1,at:0});if(['mixed','questions'].includes(mode))for(const c of x.wrongQuestions.filter(c=>!c.resolved))items.push({id:c.id,sourceRecordId:c.id,kind:'question',snapshot:clone(c),mode:'saved',order:1,at:0});for(const i of items){const h=(x.reviewRounds||[]).flatMap(r=>r.results).filter(r=>r.sourceRecordId===i.sourceRecordId);i.at=h.length?Date.parse(h.at(-1).at)||0:0;}items.sort((a,b)=>a.at-b.at||a.order-b.order||a.id.localeCompare(b.id));return {id:'round-'+Date.now()+'-'+Math.random().toString(36).slice(2,8),startedAt:new Date().toISOString(),index:0,items:items.slice(0,Math.max(1,Math.min(20,Number(limit)||5))),results:[],draft:{}};}
function recordResult(r,{rating,guess='',chosen}={}){const i=r.items[r.index];if(!i)throw Error('本轮已结束。');if(!['known','uncertain','wrong-sense'].includes(rating))throw Error('请选择本次理解情况。');if(i.kind==='question'&&!i.snapshot.question.choices.some(c=>c.id===chosen))throw Error('请先作答，再核对。');const result={id:JSON.stringify([r.id,r.index]),sourceRecordId:i.sourceRecordId,kind:i.kind,mode:i.mode,rating,guess:String(guess).slice(0,5000),snapshot:clone(i.snapshot),at:new Date().toISOString(),...(i.kind==='question'?{chosen,correct:chosen===i.snapshot.question.answer}:{})};r.results.push(result);r.index++;r.draft={};return result;}
function summary(x){const r=(x.reviewRounds||[]).flatMap(r=>r.results),s=r.filter(r=>r.kind!=='question'),q=r.filter(r=>r.kind==='question');return {rounds:(x.reviewRounds||[]).length,selfTotal:s.length,selfKnown:s.filter(r=>r.rating==='known').length,selfUncertain:s.filter(r=>r.rating==='uncertain').length,selfWrong:s.filter(r=>r.rating==='wrong-sense').length,objectiveTotal:q.length,objectiveCorrect:q.filter(r=>r.correct).length,transfer:r.filter(r=>r.mode==='transfer').length,pending:(x.pendingSentences||[]).filter(r=>r.status==='pending').length};}
function validQuestion(q){return q&&text(q.prompt,2000)&&q.prompt.trim()&&text(q.explanation,5000)&&q.explanation.trim()&&Array.isArray(q.choices)&&q.choices.length===4&&q.choices.every(c=>c&&text(c.id,80)&&text(c.text,2000)&&c.text.trim())&&new Set(q.choices.map(c=>c.id)).size===4&&q.choices.some(c=>c.id===q.answer)&&Array.isArray(q.evidence)&&q.evidence.length>0&&q.evidence.every(e=>e&&Number.isInteger(e.paragraph)&&e.paragraph>0&&text(e.quote,10000)&&e.quote.trim());}
function validRound(r){return r&&text(r.id,200)&&Array.isArray(r.items)&&r.items.length<=20&&Number.isInteger(r.index)&&r.index>=0&&r.index<=r.items.length&&Array.isArray(r.results)&&r.results.length===r.index&&r.draft&&typeof r.draft==='object'&&!Array.isArray(r.draft)&&(r.draft.guess===undefined||text(r.draft.guess,5000))&&(r.draft.chosen===undefined||text(r.draft.chosen,80))&&r.items.every(i=>i&&['word','sentence','question'].includes(i.kind)&&text(i.sourceRecordId,50000)&&['transfer','saved'].includes(i.mode)&&i.snapshot&&text(i.snapshot.articleKey,200)&&(i.kind==='word'?['word','sense','context','allowed','wordKey'].every(k=>text(i.snapshot[k])):i.kind==='sentence'?validSentence(i.snapshot):validQuestion(i.snapshot.question)))&&r.results.every((v,n)=>v&&v.sourceRecordId===r.items[n].sourceRecordId&&['known','uncertain','wrong-sense'].includes(v.rating)&&v.kind===r.items[n].kind&&v.mode===r.items[n].mode&&JSON.stringify(v.snapshot)===JSON.stringify(r.items[n].snapshot)&&(v.kind!=='question'||r.items[n].snapshot.question.choices.some(c=>c.id===v.chosen)&&v.correct===(v.chosen===r.items[n].snapshot.question.answer)));}
function validateExtra(x){const e=[];for(const k of ['pendingSentences','removedPending','lookupWords','reviewRounds'])if(x[k]!==undefined&&(!Array.isArray(x[k])||x[k].length>10000))e.push('学习扩展 '+k+' 无效。');if(Array.isArray(x.pendingSentences)&&x.pendingSentences.some(s=>!validSentence(s)||!['pending','analyzed'].includes(s.status)))e.push('疑句快照无效。');if(Array.isArray(x.removedPending)&&x.removedPending.some(s=>!validSentence(s)))e.push('疑句撤销记录无效。');if(Array.isArray(x.lookupWords)&&x.lookupWords.some(w=>!w||!text(w.id,50000)||!text(w.text,100)||!w.text.trim()||!text(w.articleKey,200)||!Number.isInteger(w.paragraph)||w.paragraph<0||!text(w.context)||w.note!==undefined&&!text(w.note,2000)))e.push('待查词快照无效。');if(x.reviewSession!==undefined&&x.reviewSession!==null&&!validRound(x.reviewSession))e.push('未完成复习回合无效。');if(Array.isArray(x.reviewRounds)&&x.reviewRounds.some(r=>!validRound(r)||r.index!==r.items.length))e.push('复习回合记录无效。');for(const k of ['difficulty','verifications'])if(x[k]!==undefined&&(!x[k]||typeof x[k]!=='object'||Array.isArray(x[k])))e.push(k+' 无效。');if(x.difficulty&&Object.values(x.difficulty).some(v=>!v||!['easy','ok','hard'].includes(v.level)||!text(v.sourceSignature,200)))e.push('难度反馈无效。');if(x.verifications&&Object.values(x.verifications).some(v=>!v||!text(v.signature,200)||!text(v.at,100)))e.push('内容核验记录无效。');if(x.returnPoint!==undefined&&x.returnPoint!==null&&(!x.returnPoint.reader||!text(x.returnPoint.reader.key,200)||!Number.isFinite(x.returnPoint.reader.scroll)||x.returnPoint.reader.scroll<0||!['reading','sentence','review','translation','vocabulary'].includes(x.returnPoint.reader.tab)||!text(x.returnPoint.activity,100)))e.push('返回阅读现场记录无效。');for(const k of ['pendingSentences','lookupWords','reviewRounds'])if(Array.isArray(x[k])&&new Set(x[k].map(r=>r.id)).size!==x[k].length)e.push('学习扩展记录存在重复 ID。');if(x.lastBackupAt!==undefined&&(!text(x.lastBackupAt,100)||!Number.isFinite(Date.parse(x.lastBackupAt))))e.push('备份时间无效。');return e;}
function lookup(data,value,batch){const q=value.trim().toLowerCase();return Object.entries(data.words).filter(([k,w])=>w.word.toLowerCase()===q||w.uses.some(u=>u.form.toLowerCase()===q)).map(([key,w])=>({key,word:w.word,allowed:w.allowed,current:key.includes('::')?key.startsWith(batch+'::'):batch==='original'})).sort((a,b)=>Number(b.current)-Number(a.current));}
function dictionaryRows(p){if(!Array.isArray(p))return [];return p.slice(0,3).flatMap(e=>(Array.isArray(e.meanings)?e.meanings:[]).slice(0,5).flatMap(m=>(Array.isArray(m.definitions)?m.definitions:[]).slice(0,3).filter(d=>text(d.definition,3000)&&d.definition.trim()).map(d=>({partOfSpeech:text(m.partOfSpeech,100)?m.partOfSpeech:'',definition:d.definition,example:text(d.example,3000)?d.example:''})))).slice(0,12);}
const api={clone,validSentence,capture,transfer,buildRound,recordResult,summary,validateExtra,lookup,dictionaryRows};if(node)module.exports=api;else root.StudyExperienceCore=api;
})(typeof window!=='undefined'?window:globalThis);
