/* Commit-aware workspace storage with atomic restore and conflict prevention. */
window.StudyState=(()=>{'use strict';const C=window.StudyWorkspaceCore;let db=null,value=null,timer,writing=Promise.resolve(),revision=0,written=0,warning='',restoring=false,phase='loading',savedAt=0,head=null,stale=false;const owner='page-'+Date.now()+'-'+Math.random().toString(36).slice(2),legacy={reader:'english-study.reader.v1',learning:'english-study.learning.v1'},channel=typeof BroadcastChannel==='function'?new BroadcastChannel('english-study.workspace'):null;
function report(p,message=''){phase=p;document.dispatchEvent(new CustomEvent('study-save-state',{detail:{phase:p,message,savedAt}}));}function conflict(){stale=true;warning='另一个页面已更新学习数据。请先导出本页未保存内容，再重新打开页面。';report('conflict',warning);}
if(channel)channel.onmessage=e=>{if(e.data?.owner!==owner)conflict();};
function readLegacy(k,fallback){try{return JSON.parse(localStorage.getItem(legacy[k])||'null')||fallback;}catch{return fallback;}}const defaults=()=>({reader:readLegacy('reader',{}),learning:window.StudyLearningCore.load(readLegacy('learning',null)),extra:C.emptyExtra()});
function mirror(v){for(const k of Object.keys(legacy))try{localStorage.setItem(legacy[k],JSON.stringify(v[k]));}catch{}}
async function open(){if(value)return;value=defaults();db=await new Promise(resolve=>{let settled=false;const done=v=>{if(settled){v?.close();return;}settled=true;clearTimeout(t);resolve(v);},t=setTimeout(()=>done(null),4000);try{const q=indexedDB.open('english-study.packages.v1',2);q.onupgradeneeded=()=>{if(!q.result.objectStoreNames.contains('packs'))q.result.createObjectStore('packs',{keyPath:'key'});if(!q.result.objectStoreNames.contains('workspace'))q.result.createObjectStore('workspace',{keyPath:'key'});};q.onsuccess=()=>{q.result.onversionchange=()=>{q.result.close();db=null;warning='数据结构已更新，请导出本页后重新打开。';report('error',warning);};done(q.result);};q.onerror=q.onblocked=()=>done(null);}catch{done(null);}});if(db)try{const saved=await transaction(['workspace'],'readonly',tx=>tx.objectStore('workspace').get('current'));if(saved?.data){head=saved.token||null;savedAt=saved.savedAt||0;value=saved.data;value.extra={...C.emptyExtra(),...value.extra};}else{revision++;await flush();}}catch(e){warning='读取或迁移失败，旧记录仍保留。'+e.message;report('error',warning);}if(!db){warning='浏览器未允许持久保存，记录仅在本页暂存。';report('error',warning);}else if(!warning)report('saved');}
function transaction(stores,mode,action){return new Promise((resolve,reject)=>{if(!db){reject(Error('浏览器未允许本机保存，请导出备份。'));return;}try{const tx=db.transaction(stores,mode);let result;const req=action(tx);if(req)req.onsuccess=()=>result=req.result;tx.oncomplete=()=>resolve(result);tx.onabort=tx.onerror=()=>reject(tx.error||Error('保存事务失败，原记录保持不变。'));}catch(e){reject(e);}});}
function guarded(tx,action){const q=tx.objectStore('workspace').get('current');q.onsuccess=()=>{if(stale||(q.result?.token||null)!==head){conflict();tx.abort();return;}action();};}
function get(k,fallback){return value?.[k]??fallback;}function set(k,v){if(restoring)return false;value[k]=C.clone(v);revision++;report(stale?'conflict':'saving',warning);clearTimeout(timer);timer=setTimeout(()=>flush().catch(()=>{}),120);return !!db;}
function failed(e){warning=stale?warning:e.message;report(stale?'conflict':'error',warning);document.dispatchEvent(new CustomEvent('study-storage-warning',{detail:warning}));}
function flush(){clearTimeout(timer);writing=writing.catch(()=>{}).then(async()=>{if(stale)throw Error(warning);if(written===revision)return;if(!db)throw Error('记录仅在本页暂存，未能写入浏览器。');const target=revision,snapshot=C.clone(value),token=owner+':'+target+':'+Date.now(),at=Date.now();report('saving');await transaction(['workspace'],'readwrite',tx=>guarded(tx,()=>tx.objectStore('workspace').put({key:'current',data:snapshot,token,savedAt:at})));head=token;written=target;savedAt=at;warning='';mirror(snapshot);channel?.postMessage({owner,token});report(written===revision?'saved':'saving');});writing.catch(failed);return writing;}
async function packs(){return transaction(['packs'],'readonly',tx=>tx.objectStore('packs').getAll());}
async function writePacks(action){await flush();const token=owner+':packages:'+Date.now(),at=Date.now(),snapshot=C.clone(value),target=revision;try{await transaction(['packs','workspace'],'readwrite',tx=>guarded(tx,()=>{action(tx.objectStore('packs'));tx.objectStore('workspace').put({key:'current',data:snapshot,token,savedAt:at});}));head=token;savedAt=at;written=target;channel?.postMessage({owner,token});report(written===revision?'saved':'saving');}catch(e){failed(e);throw e;}}
async function restore(backup,base){if(restoring)throw Error('正在恢复，请稍候。');const valid=C.validateBackup(backup);if(!valid.ok)throw Error(valid.errors[0]);await flush();restoring=true;try{const before=await packs(),data=C.clone(backup.state),token=owner+':restore:'+Date.now(),at=Date.now();data.extra={...C.emptyExtra(),...data.extra};if(!data.extra.edits.original&&C.hash(base)!==C.hash(backup.base))data.extra.edits.original={payload:C.clone(backup.base),baseHash:C.hash(base),restored:true,at};await transaction(['packs','workspace'],'readwrite',tx=>guarded(tx,()=>{const p=tx.objectStore('packs'),w=tx.objectStore('workspace');w.put({key:'rollback',data:C.clone(value),packs:before});p.clear();backup.packs.forEach(payload=>p.put({key:'local:'+payload.id,source:'local',payload:C.clone(payload)}));w.put({key:'current',data,token,savedAt:at});}));head=token;savedAt=at;value=data;revision++;written=revision;warning='';mirror(value);channel?.postMessage({owner,token});report('saved');}catch(e){failed(e);throw e;}finally{restoring=false;}}
async function rollback(){await flush();const old=await transaction(['workspace'],'readonly',tx=>tx.objectStore('workspace').get('rollback'));if(!old)throw Error('没有可回退的恢复记录。');restoring=true;try{const token=owner+':rollback:'+Date.now(),at=Date.now();await transaction(['packs','workspace'],'readwrite',tx=>guarded(tx,()=>{const p=tx.objectStore('packs'),w=tx.objectStore('workspace');p.clear();old.packs.forEach(r=>p.put(r));w.put({key:'current',data:old.data,token,savedAt:at});w.delete('rollback');}));head=token;savedAt=at;value=old.data;value.extra={...C.emptyExtra(),...value.extra};revision++;written=revision;warning='';mirror(value);channel?.postMessage({owner,token});report('saved');}catch(e){failed(e);throw e;}finally{restoring=false;}}
window.addEventListener('pagehide',()=>flush().catch(()=>{}));return {open,get,set,flush,restore,rollback,packs,writePacks,transaction,database:()=>db,warning:()=>warning,status:()=>({phase,message:warning,savedAt}),retry:flush};})();
