const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');const E=require('../experience-core'),C=require('../workspace-core'),P=require('../package-core'),L=require('../learning-core'),I=require('../import-core');const template=JSON.parse(fs.readFileSync(__dirname+'/../downloads/pack-template.json','utf8'));function source(){const p=C.clone(template);p.id='round-fixture';return {p,data:P.validate(p).compiled};}function word(data){const k=Object.keys(data.words).find(k=>data.words[k].uses.length);return L.usage(data,k,data.words[k].uses[0]);}
test('pending capture snapshots and deduplicates without losing the source',()=>{const {data}=source(),s=L.articleSentences(data.articles[0])[0],x=C.emptyExtra();assert.equal(E.capture(x,s),true);s.en='changed';assert.notEqual(x.pendingSentences[0].en,s.en);assert.equal(E.capture(x,C.clone(x.pendingSentences[0])),false);assert.equal(x.pendingSentences.length,1);assert.deepEqual(E.validateExtra(x),[]);});
test('transfer requires another genuine context and the same recorded sense',()=>{const {data}=source(),c=word(data),w=data.words[c.wordKey],u=w.uses[0],a=data.articles[0];a.plain.push(`We ${u.form} the result carefully.`);a.translations.push('参考');w.uses.push({...u,paragraph:a.plain.length-1,start:3,sense:'另一个义项'});assert.equal(E.transfer(data,c),null);w.uses.at(-1).sense=c.sense;const next=E.transfer(data,c);assert.equal(next.sense,c.sense);assert.notEqual(next.context,c.context);assert.equal(L.locate(data,next).paragraph,a.plain.length-1);});
test('round limits and unreviewed priority are retained across completed sessions',()=>{const {data}=source(),state=L.empty(),x=C.emptyExtra(),c=word(data);state.cards=[c,{...c,id:'second'}];let r=E.buildRound(data,state,x,{limit:1});E.recordResult(r,{rating:'known'});x.reviewRounds.push(r);r=E.buildRound(data,state,x,{limit:1});assert.equal(r.items[0].sourceRecordId,'second');assert.equal(r.items.length,1);assert.deepEqual(E.validateExtra(x),[]);});
test('unsupported self-ratings do not advance or create a result',()=>{const {data}=source(),state=L.empty(),x=C.emptyExtra();state.cards=[word(data)];const r=E.buildRound(data,state,x);assert.throws(()=>E.recordResult(r,{rating:'automatic-mastered'}));assert.equal(r.index,0);assert.equal(r.results.length,0);});
test('objective correctness stays separate from known self-ratings',()=>{const {data}=source(),x=C.emptyExtra(),q={id:'q',prompt:'Question?',choices:['a','b','c','d'].map(id=>({id,text:id})),answer:'b',explanation:'说明',evidence:[{paragraph:1,quote:data.articles[0].plain[0]}]};x.wrongQuestions=[{id:'wrong',articleKey:data.articles[0].key,question:q}];const r=E.buildRound(data,L.empty(),x,{mode:'questions'});assert.throws(()=>E.recordResult(r,{rating:'known'}));assert.equal(r.index,0);const result=E.recordResult(r,{rating:'known',chosen:'a'});assert.equal(result.correct,false);x.reviewRounds.push(r);const s=E.summary(x);assert.equal(s.selfTotal,0);assert.equal(s.objectiveCorrect,0);assert.equal(s.objectiveTotal,1);assert.deepEqual(E.validateExtra(x),[]);});
test('unfinished reviews, pending drafts and lookup notes survive backup merge',()=>{const ctx={window:{}};vm.runInNewContext(fs.readFileSync(__dirname+'/../content.js','utf8'),ctx);const {p,data}=source(),x=C.emptyExtra(),state=L.empty();state.cards=[word(data)];x.reviewSession=E.buildRound(data,state,x);x.reviewSession.draft.guess='未完成的判断';E.capture(x,L.articleSentences(data.articles[0])[0]);x.lookupWords=[{id:'lookup',text:'carefully',context:data.articles[0].plain[0],articleKey:data.articles[0].key,paragraph:0,note:'待核查'}];const b={format:'english-study-backup',version:1,base:C.originalPack(ctx.window.READING_DATA),packs:[p],state:{reader:{},learning:state,extra:x}};assert.equal(C.validateBackup(b).ok,true);const merged=C.restorePlan(b,b).backup;assert.equal(merged.state.extra.pendingSentences.length,1);assert.equal(merged.state.extra.reviewSession.draft.guess,'未完成的判断');assert.equal(merged.state.extra.lookupWords.length,1);});
test('backups reject fabricated result snapshots and duplicate pending IDs',()=>{const {data}=source(),x=C.emptyExtra(),state=L.empty();state.cards=[word(data)];const r=E.buildRound(data,state,x);E.recordResult(r,{rating:'known'});x.reviewRounds=[r];r.results[0].snapshot.sense='fabricated';assert.ok(E.validateExtra(x).length);x.reviewRounds=[];E.capture(x,L.articleSentences(data.articles[0])[0]);x.pendingSentences.push(C.clone(x.pendingSentences[0]));assert.ok(E.validateExtra(x).length);});
test('optional analyses retain exact genuine quotes in sentence snapshots',()=>{const {p}=source(),en=L.sentences(p.articles[0].paragraphs[0].en)[0].en;p.topics=['科技'];p.articles[0].paragraphs[0].analysis=[{quote:en,core:'主干',logic:'因果'}];let r=P.validate(p);assert.equal(r.ok,true);assert.equal(L.articleSentences(r.compiled.articles[0])[0].analysis.core,'主干');assert.deepEqual(r.compiled.articles[0].topics,['科技']);p.articles[0].paragraphs[0].analysis[0].quote='A fabricated sentence.';assert.equal(P.validate(p).ok,false);});
test('analysis changes full verification hash without changing the English quiz source',()=>{const {p}=source(),a=p.articles[0],before=C.hash(a),sig=P.signature(a);a.paragraphs[0].analysis=[{quote:L.sentences(a.paragraphs[0].en)[0].en,note:'提示'}];assert.equal(P.signature(a),sig);assert.notEqual(C.hash(a),before);});
test('local lookup keeps source-specific senses and does not invent stemming matches',()=>{const {data}=source(),w=data.words[Object.keys(data.words)[0]];assert.equal(E.lookup(data,w.word,'round-fixture')[0].allowed,w.allowed);assert.equal(E.lookup(data,w.word+'xyz','round-fixture').length,0);});
test('dictionary extraction bounds records and rejects malformed definitions',()=>{const rows=E.dictionaryRows([{meanings:[{partOfSpeech:'verb',definitions:[{definition:'Safe definition',example:'Actual example'},{definition:{bad:true}}]}]}]);assert.equal(rows.length,1);assert.equal(rows[0].example,'Actual example');assert.deepEqual(E.dictionaryRows({meanings:[]}),[]);});
test('batch import rejects all files if any is corrupt or IDs repeat',()=>{const {p}=source();let r=I.batch([{name:'good',text:JSON.stringify(p)},{name:'bad',text:'{'}]);assert.equal(r.ok,false);assert.equal(r.rows.length,0);r=I.batch([{text:JSON.stringify(p)},{text:JSON.stringify(p)}]);assert.equal(r.ok,false);const q=C.clone(p);q.id='another-batch';r=I.batch([{text:JSON.stringify(p)},{text:JSON.stringify(q)}]);assert.equal(r.ok,true);assert.equal(r.rows.length,2);});
test('manual feedback rejects unsupported mastery labels',()=>{const x=C.emptyExtra();x.difficulty.x={level:'mastered',sourceSignature:'x'};assert.ok(E.validateExtra(x).length);x.difficulty={};x.verifications.x={signature:'hash',at:'2026-10-01'};assert.deepEqual(E.validateExtra(x),[]);});

test('original revisions preserve unverified hints only at unchanged genuine positions',()=>{const ctx={window:{}};vm.runInNewContext(fs.readFileSync(__dirname+'/../content.js','utf8'),ctx);const d=ctx.window.READING_DATA,p=C.originalPack(d),mapped=C.remapOriginal(P.validate(p).compiled),a=P.preserveLegacyHints(mapped.articles[0],d.articles[0],mapped.words);assert.equal(a.words.length,d.articles[0].words.length);const html=a.paragraphs.join(' ');assert.match(html,/data-word="one"[^>]*>One<\/strong>/);assert.equal((html.match(/data-use=/g)||[]).length,mapped.articles[0].paragraphs.join(' ').match(/data-use=/g).length);const changed=C.clone(mapped.articles[0]);changed.plain[0]+=' Additional text.';changed.paragraphs[0]+=' Additional text.';const revised=P.preserveLegacyHints(changed,d.articles[0],mapped.words);assert.equal(revised.paragraphs[0].includes('data-word="one"'),false);assert.equal(L.resolveUse({articles:[a],words:mapped.words},'one',{article:1,paragraph:0,form:'One'}),null);});

test('typed lookup binds to a genuine matching sentence or stays unbound',()=>{const {data}=source(),a=data.articles[0],first=L.articleSentences(a)[0],s=E.lookupSnapshot(a,'measured',first);assert.match(s.context,/measured/);assert.notEqual(s.context,first.en);assert.equal(E.lookupSnapshot(a,'absentword').context,'');assert.equal(E.lookupSnapshot(a,'measure').context,'');});
test('conflicting original copies preserve new round and sentence snapshots consistently',()=>{const ctx={window:{}};vm.runInNewContext(fs.readFileSync(__dirname+'/../content.js','utf8'),ctx);const base=C.originalPack(ctx.window.READING_DATA),data=C.remapOriginal(P.validate(base).compiled),state=L.empty(),x=C.emptyExtra();state.cards=[L.usage(data,'portable',data.words.portable.uses[0])];x.reviewSession=E.buildRound(data,state,x);const finished=C.clone(x.reviewSession);E.recordResult(finished,{rating:'known'});x.reviewRounds=[finished];E.capture(x,L.articleSentences(data.articles[0])[0]);const current={format:'english-study-backup',version:1,base:C.clone(base),packs:[],state:{reader:{},learning:L.empty(),extra:C.emptyExtra()}},incoming={...C.clone(current),state:{reader:{},learning:state,extra:x}};incoming.base.words[0].allowed+='（备份修订）';const plan=C.restorePlan(current,incoming,'merge','copy');assert.equal(C.validateBackup(plan.backup).ok,true);assert.match(plan.backup.state.extra.pendingSentences[0].articleKey,/^original-copy-/);assert.equal(E.validateExtra(plan.backup.state.extra).length,0);assert.notEqual(plan.backup.state.extra.reviewSession.items[0].snapshot.wordKey,'portable');});
test('backup previews count unavailable sentence and lookup sources without crashing on malformed arrays',()=>{const ctx={window:{}};vm.runInNewContext(fs.readFileSync(__dirname+'/../content.js','utf8'),ctx);const {data}=source(),x=C.emptyExtra(),s=L.articleSentences(data.articles[0])[0];E.capture(x,s);x.lookupWords=[{id:'lookup-missing',text:'measured',articleKey:s.articleKey,paragraph:0,context:'',note:''}];const b={format:'english-study-backup',version:1,base:C.originalPack(ctx.window.READING_DATA),packs:[],state:{reader:{},learning:L.empty(),extra:x}};assert.equal(C.validateBackup(b).summary.missing,2);b.state.extra.pendingSentences={bad:true};assert.equal(C.validateBackup(b).ok,false);});
