const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const C=require('../workspace-core'),L=require('../learning-core');
const content={window:{}};vm.runInNewContext(fs.readFileSync(__dirname+'/../content.js','utf8'),content);const base=C.originalPack(content.window.READING_DATA),pack=JSON.parse(fs.readFileSync(__dirname+'/../downloads/pack-template.json','utf8'));
function fakeDatabase(){
 const stores=new Map([['packs',new Map()]]),state={fail:false};
 const db={close(){},objectStoreNames:{contains:k=>stores.has(k)},createObjectStore:k=>stores.set(k,new Map()),transaction(names,mode){
  const active=new Map(names.map(n=>[n,new Map([...stores.get(n)].map(([k,v])=>[k,structuredClone(v)]))])),requests=[],tx={error:null,aborted:false,abort(){this.aborted=true;this.error=new Error('transaction aborted');},objectStore(n){const map=active.get(n);return {get(k){const q={};requests.push(()=>{q.result=structuredClone(map.get(k));q.onsuccess?.();});return q;},getAll(){const q={};requests.push(()=>{q.result=structuredClone([...map.values()]);q.onsuccess?.();});return q;},put(v){map.set(v.key,structuredClone(v));return {};},delete:k=>map.delete(k),clear:()=>map.clear()};}};
  setTimeout(()=>{if(mode==='readwrite'&&state.fail){state.fail=false;tx.error=new Error('simulated quota failure');tx.onabort?.();return;}requests.forEach(fn=>fn());if(tx.aborted){tx.onabort?.();return;}if(mode==='readwrite')for(const[n,m]of active)stores.set(n,m);tx.oncomplete?.();},0);return tx;
 }};
 return {stores,state,indexedDB:{open(){const q={result:db};setTimeout(()=>{q.onupgradeneeded?.();q.onsuccess?.();},0);return q;}}};
}
async function setup(){const f=fakeDatabase(),legacy=new Map([['english-study.reader.v1',JSON.stringify({readKeys:['original/1']})]]),ctx={window:{StudyWorkspaceCore:C,StudyLearningCore:L,addEventListener(){}},indexedDB:f.indexedDB,localStorage:{getItem:k=>legacy.get(k),setItem:(k,v)=>legacy.set(k,v)},document:{dispatchEvent(){}},CustomEvent:class{},setTimeout,clearTimeout};vm.runInNewContext(fs.readFileSync(__dirname+'/../workspace-store.js','utf8'),ctx);await ctx.window.StudyState.open();return {...f,S:ctx.window.StudyState,legacy};}
const incoming=()=>({format:'english-study-backup',version:1,base:C.clone(base),packs:[C.clone(pack)],state:{reader:{readKeys:['original/2'],settings:{theme:'dark'}},learning:L.empty(),extra:C.emptyExtra()}});
test('storage migrates legacy reader without deleting old keys',async()=>{const {S,legacy,stores}=await setup();assert.deepEqual(JSON.parse(JSON.stringify(S.get('reader').readKeys)),['original/1']);assert.ok(legacy.has('english-study.reader.v1'));assert.ok(stores.get('workspace').has('current'));});
test('failed restore transaction leaves source packages and current state intact',async()=>{const {S,state,stores}=await setup();const before=JSON.stringify(stores.get('workspace').get('current'));state.fail=true;await assert.rejects(S.restore(incoming(),base),/quota/);assert.equal(JSON.stringify(stores.get('workspace').get('current')),before);assert.equal(stores.get('packs').size,0);assert.deepEqual(JSON.parse(JSON.stringify(S.get('reader').readKeys)),['original/1']);assert.equal(stores.get('workspace').has('rollback'),false);});
test('successful restore and rollback atomically swap all packages state and legacy hints',async()=>{const {S,stores,legacy}=await setup();await S.restore(incoming(),base);assert.equal(stores.get('packs').size,1);assert.deepEqual(JSON.parse(JSON.stringify(S.get('reader').readKeys)),['original/2']);assert.ok(stores.get('workspace').has('rollback'));await S.rollback();assert.equal(stores.get('packs').size,0);assert.deepEqual(JSON.parse(JSON.stringify(S.get('reader').readKeys)),['original/1']);assert.deepEqual(JSON.parse(legacy.get('english-study.reader.v1')).readKeys,['original/1']);});
test('restore retains explicit original edits when backup baseline differs',async()=>{const {S}=await setup(),b=incoming();b.base.articles[0].zhTitle='旧基线';b.state.extra.edits.original={payload:C.clone(base),baseHash:C.hash(base)};b.state.extra.edits.original.payload.articles[0].zhTitle='明确修订';await S.restore(b,base);assert.equal(S.get('extra').edits.original.payload.articles[0].zhTitle,'明确修订');});
test('failed write never reports saved or updates legacy hints, and retry commits',async()=>{const {S,state,stores,legacy}=await setup(),before=JSON.stringify(stores.get('workspace').get('current'));state.fail=true;S.set('reader',{readKeys:['original/3']});assert.equal(S.status().phase,'saving');await assert.rejects(S.flush(),/quota/);assert.equal(S.status().phase,'error');assert.equal(JSON.stringify(stores.get('workspace').get('current')),before);assert.deepEqual(JSON.parse(legacy.get('english-study.reader.v1')).readKeys,['original/1']);await S.retry();assert.equal(S.status().phase,'saved');assert.deepEqual(JSON.parse(legacy.get('english-study.reader.v1')).readKeys,['original/3']);});
test('foreign committed head prevents stale page overwrite',async()=>{const {S,stores,legacy}=await setup(),saved=stores.get('workspace').get('current');saved.token='another-page';saved.data.reader={readKeys:['original/4']};S.set('reader',{readKeys:['original/5']});await assert.rejects(S.flush());assert.equal(S.status().phase,'conflict');assert.deepEqual(stores.get('workspace').get('current').data.reader.readKeys,['original/4']);assert.deepEqual(JSON.parse(legacy.get('english-study.reader.v1')).readKeys,['original/1']);});
test('batch quota failure adds no packages, successful retry writes both atomically',async()=>{const {S,state,stores}=await setup();state.fail=true;await assert.rejects(S.writePacks(p=>{p.put({key:'local:a',payload:pack});p.put({key:'local:b',payload:pack});}));assert.equal(stores.get('packs').size,0);await S.writePacks(p=>{p.put({key:'local:a',payload:pack});p.put({key:'local:b',payload:pack});});assert.equal(stores.get('packs').size,2);});
